config/routes.rb
Rails.application.routes.draw do
  root to: 'summary#index'
  resources :transactions
  resources :accounts
  get '/summary', to: 'summary#index'

  namespace :api do
    namespace :v1 do
      resources :transactions
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :account_transactions, dependent: :destroy

    # def credit(amount)
    # 	self.transactions.create(amount: -(amount.to_f))
    # end

    # def debit(amount)
    # 	self.transactions.create(amount: amount.to_f)
    # end
end

app/models/account_transaction.rb
class AccountTransaction < ApplicationRecord
    belongs_to :account

    def self.create_credit_transaction(data)
    	self.create({
    		transaction_id: data[:transaction_id],
    		account_id: data[:account].id, 
    		transaction_date: data[:transaction_date],
    		comments: data[:comments],
    		amount: -(data[:amount].to_f)
    	})
    end

    def self.create_debit_transaction(data)
    	self.create({
    		transaction_id: data[:transaction_id],
    		account_id: data[:account].id, 
    		transaction_date: data[:transaction_date],
    		comments: data[:comments],
    		amount: data[:amount].to_f
    	})
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /accounts
  # GET /accounts.json
  def index
    @accounts = Account.all
  end

  # GET /accounts/1
  # GET /accounts/1.json
  def show
  end

  # GET /accounts/new
  def new
    @account = Account.new
  end

  # GET /accounts/1/edit
  def edit
  end

  # POST /accounts
  # POST /accounts.json
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: 'Account was successfully created.' }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accounts/1
  # PATCH/PUT /accounts/1.json
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: 'Account was successfully updated.' }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accounts/1
  # DELETE /accounts/1.json
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: 'Account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = Account.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def account_params
      params.require(:account).permit(:name, :category)
    end
end

app/controllers/api/v1/transactions_controller.rb
class API::V1::TransactionsController < ApplicationController	
	protect_from_forgery with: :null_session, if: Proc.new {|c| c.request.format.json? }
	
	def index
		render json: {text: "hi", msg: "welcome to Api V1 controller"}
	end

	def create
		puts "*"*25
		puts params.inspect
		TransactionCreator.new(params).create
		render json: {status: "success"}
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/summary_controller.rb
class SummaryController < ApplicationController
  def index
    # select account_id, accounts.name, sum(amount) 
    # from transactions 
    # LEFT JOIN accounts on accounts.id = transactions.account_id  
    # group by account_id;
    # 
    @expense_summary =  AccountTransaction
                        .joins(:account)
                        .select("account_transactions.account_id, accounts.name as account_name, sum(amount) as amount")
                        .group('account_id')
    
    respond_to do |format|
      format.html {render :index}
      format.json {render json: @expense_summary}
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = AccountTransaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = AccountTransaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = AccountTransaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = AccountTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(:transaction_id, :account_id, :amount, :transaction_date, :description, :comments)
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/account_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Transaction</th>
      <th>Account</th>
      <th>Amount</th>
      <th>Transaction date</th>
      <th>Description</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_id %></td>
        <td><%= "#{transaction.account_id} -  #{transaction.account.name} "%></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.comments %></td>
        <td><%= link_to 'Show', transaction %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <% if account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @accounts.each do |account| %>
      <tr>
        <td><%= account.id %></td>
        <td><%= account.name %></td>
        <td><%= account.category %></td>
        <td><%= link_to 'Show', account %></td>
        <td><%= link_to 'Edit', edit_account_path(account) %></td>
        <td><%= link_to 'Destroy', account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/new.html.erb
<h1>New Account</h1>

<%= render 'form', account: @account %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @account.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @account.category %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PersonalExpenseTracking</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Accounts', accounts_path %> |
    <%= link_to 'Transactions', transactions_path %>
    <%= yield %>
  </body>
</html>

app/views/summary/index.html.erb
<h1>Summary#index</h1>

<table>
  <thead>
    <tr>
      <th>Account</th>      
      <th>Amount</th>      
    </tr>
  </thead>
  <tbody>
    <% @expense_summary.each do |item| %>
      <tr>
        <td><%= item.account_name %></td>
        <td><%= item.amount %></td>
      </tr>
    <% end %>
  </tbody>  
</table>
    

app/views/transactions/_form.html.erb
<%= form_with(model: transaction, local: true) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :transaction_id %>
    <%= form.text_field :transaction_id %>
  </div>

  <div class="field">
    <%= form.label :account_id %>
    <%= form.number_field :account_id %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="field">
    <%= form.label :transaction_date %>
    <%= form.datetime_select :transaction_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Transactions</h1>

<table>
  <thead>
    <tr>
      <th>Transaction</th>
      <th>Account</th>
      <th>Amount</th>
      <th>Transaction date</th>
      <th>Description</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @transactions.each do |transaction| %>
      <tr>
        <td><%= transaction.transaction_id %></td>
        <td><%= "#{transaction.account_id} -  #{transaction.account.name} "%></td>
        <td><%= transaction.amount %></td>
        <td><%= transaction.transaction_date %></td>
        <td><%= transaction.description %></td>
        <td><%= transaction.comments %></td>
        <td><%= link_to 'Show', transaction_path(transaction.transaction_id) %></td>
        <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
        <td><%= link_to 'Destroy', transaction_path(transaction.transaction_id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Transaction', new_transaction_path %>

app/views/transactions/new.html.erb
<h1>New Transaction</h1>

<%= render 'form', transaction: @transaction %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Transaction:</strong>
  <%= @transaction.transaction_id %>
</p>

<p>
  <strong>Account:</strong>
  <%= @transaction.account_id %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @transaction.amount %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @transaction.transaction_date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @transaction.description %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @transaction.comments %>
</p>

<%= link_to 'Edit', edit_transaction_path(@transaction) %> |
<%= link_to 'Back', transactions_path %>